version: '3.8'

services:
  smtp-cli:
    build: .
    container_name: smtp-cli
    network_mode: host
    environment:
      - SMTP_HOST=localhost
      - SMTP_PORT=2525
    volumes:
      - ./:/app
    working_dir: /app
    command: ["smtp-cli", "help"]
